stages:
  - build
  - deploy

build client:
  stage: build
  image: node:18
  script:
    - cd client
    - npm install
    - npm run build

#deploy client:
#  stage: deploy
#  script:
#    - phploy -s ...
