stages:
  - build
  - deploy

build client:
  stage: build
  image: node:18
  script:
    - cd client
    - npm install
    - npm run build
  artifacts:
    paths:
      - client/build

deploy client:
  stage: deploy
  image:
    name: pockost/phploy:4.9.3
    entrypoint: [""]
  script:
    - phploy -s client-prod
